Add extension layout and Theme functions for label, pinkButton, shadowView
MariaGlushtsova/BudgetTrackerMDF pull request #4
Opened 2023-08-11 11:22 UTC by i0240

2023-08-17 17:33 UTC, sooitgoes approved these changes

2023-08-17 17:35 UTC, sooitgoes approved these changes

2023-08-18 17:18 UTC, MariaGlushtsova approved these changes

2023-08-18 19:17 UTC, Amoforever approved these changes

2023-08-23 05:07 UTC, nskazakov requested changes

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Extensions/UIView+Extensions.swift
> +    func addConstraints(top: NSLayoutYAxisAnchor? = nil,
если ты переносишь параметры, то начинай с первого
Закрывающая скобка тоже должна быть на отдельной строке

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Resources/Constants/Theme.swift
> +struct Theme {
очень хорошо. Молодец:)

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Sources/Scenes/OnboardngModel.swift
> +    var image: String
let, не var

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Sources/Scenes/OnboardingView.swift
> +        mainImageView.addConstraints(bottom: pageImageView.topAnchor,
опять таки про перенос
Начинай с первого параметра, так будет получше выглядеть

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Extensions/UIView+Extensions.swift
> +    func addSubviews(_ subviews: [UIView]) {
можно `subviews: UIView...`

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Sources/Scenes/OnboardingThirdViewController.swift
> +    init() {
а зачем, если он пустой?

Еще, можно написать базовый ViewController, в котором объявить все эти методы, чтобы потом тупо от него наследоваться и переопределять только то, что реально нужно

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Sources/Scenes/OnboardingThirdViewController.swift
> +    // MARK: - Actions
лишнее?

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Sources/Scenes/OnboardingView.swift
> +        mainImageView.image = UIImage(named: model.image)
можно вынести в какой нибудь setupView()
По аналогии с setupHierarchy

2023-08-23 05:07 UTC, nskazakov commented on BudgetTrackerMDF/Sources/Scenes/OnboardingView.swift
> +    required init?(coder: NSCoder) {
тоже можно создать базовую вьюшку и вынести туда все методы вот эти + определить основные для настройки

2023-08-31 08:06 UTC, merged

2023-08-31 09:06 UTC, nskazakov commented on BudgetTrackerMDF/Custom Views/BasicView.swift
> +class BasicView: UIView {
Base

2023-08-31 09:06 UTC, nskazakov commented on BudgetTrackerMDF/Extensions/UIView+Extensions.swift
> +                        top: NSLayoutYAxisAnchor? = nil,
исправь отступы

2023-08-31 09:06 UTC, nskazakov commented on BudgetTrackerMDF/Sources/Scenes/OnboardingThirdViewController.swift
> +class OnboardingThirdViewController: BasicViewController {
бляяяя